services:
  - type: web
    name: churn-prediction
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python model/train_model.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.12
      - key: DATABASE_URL
        value: postgresql://postgre:WyW4B4CseTdMfRTPkTV6roah03tzIn4J@dpg-d7np5giqqhas738271e0-a.ohio-postgres.render.com/churn_db_np39